
services:
  gencerts:
    image: alpine/openssl:latest
    volumes:
      - ./certs:/certs
    command: "req -new -x509 -nodes -keyout /certs/server.key -out /certs/server.crt --config /certs/openssl.cnf"
    
  webserver:
    image: nginx:latest
    depends_on:
      - gencerts
    ports:
      - 443:443
    volumes:
      - ./nginx/:/etc/nginx/conf.d/:ro
      - ./certs/:/etc/nginx/ssl/:ro

